bot:

    prompt: ">>>"

    initial_question: Hi, how can I help you today?
    default_response: Sorry, I don't have an answer for that!
    default_response_srai: YEMPTY
    empty_string: YEMPTY
    exit_response: So long, and thanks for the fish!
    exit_response_srai: YEXITRESPONSE

    override_properties: true

brain:

    # Overrides
    overrides:
      allow_system_aiml: false
      allow_learn_aiml: false
      allow_learnf_aiml: false

    # Defaults
    defaults:
      default-get: unknown
      default-property: unknown
      default-map: unknown

    # Nodes
    nodes:
      pattern_nodes: ../../ybot/config/pattern_nodes.conf
      template_nodes: ../../ybot/config/template_nodes.conf

    files:
        aiml:
            files: $BOT_ROOT/aiml
            extension: .aiml
            directories: true
            conversation:
              file: /tmp/multibot-conversation.csv
              format: csv
              delete_on_start: true
        properties: $BOT_ROOT/config/properties.txt
        preprocessors: $BOT_ROOT/config/preprocessors.conf
        postprocessors: $BOT_ROOT/config/postprocessors.conf

    services:
        PROGRAMY:
            classname: programy.services.programy.ProgramyRESTService
            method: GET
            host: 127.0.0.1
            port: 8989
            url: /api/rest/v1.0/ask

line:
  host: 127.0.0.1
  port: 8084
  debug: false
  license_keys: $BOT_ROOT/config/license.keys
